image: php

stages:
  - build
  - deploy

compile_job:
  stage: build
  tags:
  - php
  - composer
  script:
  - composer install
  - php oil test
  - php oil test --coverage-text=coverage.txt --colors=never
  - cat coverage.txt
  artifacts:
    paths:
    - coverage.txt

deployment_job:
  stage: deploy
  tags:
  - php
  - composer
  - dpl
  dependencies:
  - compile_job
  script:
  - dpl --provider=heroku --app=hidden-plains-22025 --api-key=$HEROKU_STAGING_API_KEY
